language: python
sudo: false
dist: trusty
python:
  - "3.6"
install:
  - pip install -Ir requirements.txt
  - pip install -e .[ci-test]
script:
  - pylint -d fixme colormotion/ scripts/
  - pytest --pylint-error-types=CREF
